[package]
name = "pingu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.4", features = ["derive"] }
crc = "3.0.1"
crc32fast = "1.4.0"
pretty_assertions = "1.4.0"
thiserror = "1.0.58"
